"""Train the crop model from data/Crop_recommendation.csv and write model.pkl,
feature_ranges.json and evaluation.md."""

import json
import math
import pickle
from pathlib import Path

import numpy as np
import pandas as pd
import sklearn
from sklearn.dummy import DummyClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

HERE = Path(__file__).parent
DATA = HERE / "data" / "Crop_recommendation.csv"
FEATURES = ["N", "P", "K", "temperature", "humidity", "ph", "rainfall"]
SEED = 42


def make_model():
    return BaggingClassifier(DecisionTreeClassifier(), n_estimators=10, random_state=SEED)


def feature_ranges(df):
    ranges = {}
    for f in FEATURES:
        step = 0.1 if f == "ph" else 1
        lo = math.floor(df[f].min() / step) * step
        hi = math.ceil(df[f].max() / step) * step
        ranges[f] = {"min": round(lo, 1), "max": round(hi, 1)}
    return ranges


def markdown_confusion(labels, cm):
    short = [label[:5] for label in labels]
    lines = ["| true \\ pred | " + " | ".join(short) + " |", "|---" * (len(labels) + 1) + "|"]
    for label, row in zip(labels, cm):
        lines.append(f"| {label} | " + " | ".join(str(v) if v else "." for v in row) + " |")
    return "\n".join(lines)


def main():
    df = pd.read_csv(DATA)
    X, y = df[FEATURES].to_numpy(), df["label"].to_numpy()
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=SEED
    )

    model = make_model().fit(X_train, y_train)
    pred = model.predict(X_test)
    acc = accuracy_score(y_test, pred)
    labels = sorted(np.unique(y))
    cm = confusion_matrix(y_test, pred, labels=labels)

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
    cv_scores = cross_val_score(make_model(), X, y, cv=cv)

    baselines = {
        "Majority class": DummyClassifier(strategy="most_frequent"),
        "Gaussian naive Bayes": GaussianNB(),
        "Single decision tree": DecisionTreeClassifier(random_state=SEED),
    }
    baseline_acc = {
        name: accuracy_score(y_test, m.fit(X_train, y_train).predict(X_test))
        for name, m in baselines.items()
    }

    with open(HERE / "model.pkl", "wb") as f:
        pickle.dump(model, f)
    (HERE / "feature_ranges.json").write_text(json.dumps(feature_ranges(df), indent=2) + "\n")

    errors = [
        f"- {t} predicted as {p}: {cm[i][j]}"
        for i, t in enumerate(labels)
        for j, p in enumerate(labels)
        if i != j and cm[i][j]
    ]
    report = f"""# Model evaluation

Generated by `python train.py` (scikit-learn {sklearn.__version__}). Do not edit by hand.

- Data: {len(df)} rows, {len(labels)} crops, {len(df) // len(labels)} rows per crop
- Split: stratified 80/20, seed {SEED} ({len(y_train)} train / {len(y_test)} test)
- Model: BaggingClassifier, 10 decision trees, trained on the train split only

## Held-out accuracy

**{acc:.4f}** ({int((pred == y_test).sum())}/{len(y_test)} correct)

5-fold stratified cross-validation on all rows: {cv_scores.mean():.4f} (std {cv_scores.std():.4f})

## Baselines on the same split

| Model | Held-out accuracy |
|---|---|
""" + "\n".join(f"| {n} | {a:.4f} |" for n, a in baseline_acc.items()) + f"""

## Misclassifications

{chr(10).join(errors) if errors else "- none"}

## Confusion matrix (held-out set; rows = true, columns = predicted, first 5 letters)

{markdown_confusion(labels, cm)}
"""
    (HERE / "evaluation.md").write_text(report)
    print(f"held-out accuracy {acc:.4f}; cv {cv_scores.mean():.4f}±{cv_scores.std():.4f}")
    for n, a in baseline_acc.items():
        print(f"{n}: {a:.4f}")


if __name__ == "__main__":
    main()
